name: Create checklists

on:
  # Runs on pushes targeting the main branch, only if md-files in the test case directory were changed
  push:
    branches: [ "main" ]
    paths: [ "src/03_test_cases/**.md" ]

  # Allows to run this workflow manually from the actions tab
  workflow_dispatch:

permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f scripts/requirements ]; then pip install -r scripts/requirements; fi
    - name: Run script
      run: |
        python3 scripts/create_checklists.py
    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        message: Update checklists
        add: "checklists/*"
        push: true
